services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    worker:
        build: .
        command: rq worker --url redis://redis:6379
        env_file:
            - .env
        depends_on:
            - redis
        volumes:
            - .:/app
